services:
  pgfloat:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: float
      POSTGRES_PASSWORD: float
      POSTGRES_DB: float
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  csgofloat:
    image: step7750/csgofloat:latest
    depends_on:
      - pgfloat
    ports:          # host→container
      - "3000:80"   # API bude na http://localhost:3000/
    volumes:
      - ./config:/config
    environment:
      - NODE_ENV=production
